apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  annotations:
    "sidecar.jaegertracing.io/inject": "true" # <1>
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: ghcr.io/frzifus/jaeger-otel-test:latest
        args: ["-jaeger.agent.host=localhost", "-jaeger.agent.port=6831"]
        env:
          - name: OTEL_SERVICE_NAME
            value: "frzifus-otel-test"
